name: scroll_pos
description: Provides some additional functions to ScrollController to define item position relative to the screen.
version: 0.4.0
homepage: https://github.com/WinXaito/scroll_pos

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: